
spring.datasource:
                  url: jdbc:mysql://localhost:3306/qaZonions?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
                  username: root
                  password: root
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  initialization-mode: always

spring.jpa:
           properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
           hibernate.use-new-id-generator-mappings: false
           hibernate.ddl-auto: update

# App Properties

app:
    jwtSecret:  jwtsecret
    jwtExpirationMs:  86400000

server:
  port: 8080
  
#spring.profiles.active: stage  
server.servlet.context-path: "/api"
#logging configuration

logging:
  file: logs/debug.log
  pattern: 
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.main.Restaurant_App.controller: INFO
    org.hibernate: ERROR
  
#Session Management
spring.session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION  
  
resilience4j.ratelimiter:
  instances:
    restaurantService:
      limitForPeriod: 2
      limitRefreshPeriod: 4s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


#swagger config
apps:
  name: Zonions
  api:
    title: Zonions API
    version: 1.0.0
    description: Deals with management of restaurants
    base-package: com.main.Restaurant_App
    contact-name: ZonionsGroup
    contact-email: zonionsAPI@gmail.com
    swagger:
      enable: true
