
#spring.datasource:
#                  url: jdbc:mysql://localhost:3306/MainZonions?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
#                  username: root
#                  password: root
#                  driver-class-name: com.mysql.cj.jdbc.Driver
#                  initialization-mode: always
#
#spring.jpa:
#           properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#           hibernate.use-new-id-generator-mappings: false
#           hibernate.ddl-auto: update

#Database configuration
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/MainZonions?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
        username: root
        password: root
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

#Java mail configuration
    mail:
      host: smtp.gmail.com
      port: 587
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      username: testingzonions@gmail.com
      password: testingravi@143

      
#zonions.application@gmail.com
#Zonions123
# App Properties

app:
    jwtSecret:  jwtsecret
    jwtExpirationMs:  86400000

server:
  port: 8080
  
#spring.profiles.active: stage  
server.servlet.context-path: "/api"
#logging configuration

logging:
  file: logs/debug.log
  pattern: 
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.main.Restaurant_App.controller: INFO
    org.hibernate: ERROR
  
#Session Management
spring.session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION  
  
resilience4j.ratelimiter:
  instances:
    restaurantService:
      limitForPeriod: 2
      limitRefreshPeriod: 4s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


#swagger config
apps:
  name: Zonions
  api:
    title: Zonions API
    version: 1.0.0
    description: Deals with management of restaurants
    base-package: com.main.Restaurant_App
    contact-name: ZonionsGroup
    contact-email: zonionsAPI@gmail.com
    swagger:
      enable: true
